//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.PBC.Web.Private.Pages {
    
    public partial class EditTransfer {
        protected AIM.PBC.Web.Private.Controls.Head ctrlHead;
        protected System.Web.UI.HtmlControls.HtmlForm theForm;
        protected AIM.PBC.Web.Private.Controls.Header ctrlHeader;
        protected System.Web.UI.WebControls.RadioButtonList rblType;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected AIM.PBC.Web.Private.Controls.Footer ctrlFooter;
    }
}
