//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.PBC.Web.Private.Pages {
    
    public partial class EditPercentageTransfer {
        protected AIM.PBC.Web.Private.Controls.Head ctrlHead;
        protected System.Web.UI.HtmlControls.HtmlForm theForm;
        protected AIM.PBC.Web.Private.Controls.Header ctrlHeader;
        protected AIM.PBC.Web.UI.Controls.ClientMessage ctrlClientMessage;
        protected System.Web.UI.WebControls.CustomValidator cvPage;
        protected AIM.PBC.Web.UI.Controls.AccountDropDownList ddlSourceAccount;
        protected AIM.PBC.Web.UI.Controls.AccountDropDownList ddlTargetAccount;
        protected System.Web.UI.WebControls.TextBox tbName;
        protected System.Web.UI.WebControls.TextBox tbAmount;
        protected System.Web.UI.WebControls.TextBox tbPercentage;
        protected Telerik.WebControls.RadDatePicker dpStartDate;
        protected System.Web.UI.WebControls.TextBox tbPeriod;
        protected System.Web.UI.WebControls.PlaceHolder phAddMode;
        protected System.Web.UI.WebControls.Button btnAddSubmit;
        protected System.Web.UI.WebControls.Button btnAddCancel;
        protected System.Web.UI.WebControls.PlaceHolder phEditMode;
        protected System.Web.UI.WebControls.Button btnEditSubmit;
        protected System.Web.UI.WebControls.Button btnEditCancel;
        protected AIM.PBC.Web.Private.Controls.Footer ctrlFooter;
    }
}
