//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.PBC.Web.Private.Pages {
    
    public partial class Login {
        protected AIM.PBC.Web.Private.Controls.Head ctrlHead;
        protected System.Web.UI.HtmlControls.HtmlForm theForm;
        protected AIM.PBC.Web.Private.Controls.Header ctrlHeader;
        protected AIM.PBC.Web.UI.Controls.ClientMessage ctrlClientMessage;
        protected System.Web.UI.WebControls.TextBox tbUsername;
        protected System.Web.UI.WebControls.TextBox tbPassword;
        protected System.Web.UI.WebControls.CheckBox cbPersistent;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.PlaceHolder phDebugLogin;
        protected AIM.PBC.Web.UI.Controls.Panel pnlDebugLogin;
        protected AIM.PBC.Web.Private.Controls.Footer ctrlFooter;
    }
}
